[package]
name = "forthhttp"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.2"
actix-web = "4"
hyper = "0.14.23"
rocket = "0.4.11"
tokio = "1.24.1"
lazy_static = "1.4.0"
rust-forth-compiler = "0.5.3"